### PR TITLE
a few changes

### PR DESCRIPTION
**Pull request by 75lb**
i made a few changes to demonstrate some potential improvements you could make
- the Promise return type is now a clickable link (uses `@external`)
- methods returning promises now have @fulfil and @reject tags
- moved the "operation error" details into the method description as the markdown list in the description was messing up the formatting of the tag list a bit.. put it back to see for youself, the @fulfil tag is indented

i also updated your dependencies to the latest versions..  any thoughts? Hopefully you like as i'd like to link to your README as a good example, including how to document promises..

### CODE REVIEW

**Comment by reject-zz** [comment]
Stop emailing me.

**Comment by 75lb** [comment]
you can see how these changes look here: https://github.com/75lb/tokenbucket

**Comment by jes-carr** [comment]
It looks great. I'll merge them later on.

I'm also thinking that it would be even clearer to put the operational errors in the Reject description. 

Thanks

**Comment by reject-zz** [comment]
Not sure why I'm getting included in this email chain but I don't need to
be part of it. My guess is the @reject tag because that's my username.

**Comment by 75lb** [comment]
or you could consider creating an `@enum` for the possible operation errors, as I did [here](https://github.com/75lb/handbrake-js#module_handbrake-js..Handbrake#eError).. then you can say that reject returns an error of type `eError` (or whatever you name your enum).. i think this is quite a clean solution..

**Comment by jes-carr** [comment]
Ok I just added your changes with a few modifications:
- You updated the code directly in the js file, and it should go to the coffee file.
- I really like the `external:` format, so I implemented it also for the redisClient external.
- I didn't like the @see format, because I want the link inside an Example headline, as for the rest of docs. I realised the @example tag will wrap around `js` tags if it doesn't have any `js` tag, so I created one with just one space. Not ideal. I don't think an example need to be a code snipped always, and it could be a link to an external. Hopefully you come up with a solution for a next release 
- I'd like to explain about the @reject error, but unfortunately it doesn't allow multiple lines or inline code. I'd suggest to treat is as you do for the @return tag. At the moment I put it in the @desc but hopefully I can move it to @reject soon. The @enum idea seems too complicated for this case.

I can open an issue for this suggestions. Should they go to your dmd library?

**Comment by 75lb** [comment]
sorry for the delay in actioning this! i lost my damn laptop a week ago - left it on the tube.. i'll get a new one in the next couple of days and get back on it..

**Pull request closed without merging**
